version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: buaE41oSbktcPiA9uuTc
      MYSQL_DATABASE: medical_lab
      MYSQL_USER: labtech
      MYSQL_PASSWORD: buaE41oSbktcPiA9uuTc
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
